### ISSUE TITLE
no ublast?

### ISSUE THREAD

**Issue by jianshu93** [rcedgar/usearch12#5]
Hello Robert, 

usearch  -ublast is not open source right, but I do saw usearch_local there, just some default parameter tuning for usearch_local and then we have ublast?

Thanks,

Jianshu

**Comment by rcedgar** [comment]
The story is a bit complicated because `ublast` (the command in `usearch`) and UBLAST (the algorithm described in my 2010 paper) are not the same. This is confusing, my mistake. The UBLAST algorithm is implemented in the `usearch_local` command.

The `ublast` command implemented a different algorithm which used seed indexing. This is now obsolete because [DIAMOND](https://github.com/bbuchfink/diamond) is better, I see no reason anyone would use `ublast` now unless there are some older scripts which require it.

If you want to use `ublast` for backwards compatibility with a pipeline, you can use one of the older usearch binaries which are now posted under the CC0-1.0 license: [https://github.com/rcedgar/usearch_old_binaries/](https://github.com/rcedgar/usearch_old_binaries/).

**Comment by jianshu93** [comment]
Hi Robert,

Thanks for the response. Diamond is only for amino acid index, not nt but ublast does support nt right. Yeah I can use the old binary for ublast but again I want to use it also for macOS M series CPU.  Not sure it will be widely used since Mac is still less used in real world dataset. Thanks for open source (especially the local one) for the community.

Jianshu
